### ISSUE TITLE
Error when consuming the library

### ISSUE THREAD

**Issue by acf-patrick** [mmahnic/argumentum#12]
![Sans titre](https://user-images.githubusercontent.com/55443338/209914465-89c1a6f6-6bc0-4f61-8d91-2465841d49ac.png)

I basically just used the includes and static library generated with __Cmake__ + __Visual Studio__ but I still can't compile my project.
However, the examples provided in the source code run perfectly ; perhaps because they use directly the source code instead of the build output.

**Comment by mmahnic** [comment]
I use the static version through VCPKG all the time and there are no problems.

I suspect you have another issue that is related to Windows libraries. If you look carefully at the error, it says that there is an '(' right of '::'. The problem is that Windows libraries define `min` and `max` symbols to sth like `(a < b ? a : b)`. I think this is what is causing the problem.

Try to put the following lines to your pch.h / stdafx.h after the windows includes but before argumentum includes:
```
#undef min
#undef max
```
